### ISSUE TITLE
Issue on extras/login/login

### ISSUE THREAD

**Issue by CamilleBeaute** [modxorg/Docs#416]
## Affected page(s)

https://docs.modx.com/3.x/en/extras/login/login.tutorials/using-pre-and-post-hooks#register-custom-email-posthook

## What needs to be improved?

The following code generates an HTTP ERROR 500 when using it as a posthook snippet.

```php
$message = 'Hi, a new User signed up: '.$hook->getValue('username')
 . ' with email '.$hook->getValue('email').'.';
$modx->getService('mail', 'mail.modPHPMailer');
$modx->mail->set(modMail::MAIL_BODY,$message);
$modx->mail->set(modMail::MAIL_FROM,'admin@jerrys.org');
$modx->mail->set(modMail::MAIL_FROM_NAME,'Jerrys Site');
$modx->mail->set(modMail::MAIL_SENDER,'Jerrys Site');
$modx->mail->set(modMail::MAIL_SUBJECT,'New User Signed Up');
$modx->mail->address('to','communitymanager@jerrys.com');
$modx->mail->setHTML(true);
if (!$modx->mail->send()) {
    $modx->log(modX::LOG_LEVEL_ERROR,'An error occurred while trying to send the email: '.$err);
}
$modx->mail->reset();
/* tell our snippet we're good and can continue */
return true;
```

The error within the error log: 

```
[2022-06-29 10:54:53] (ERROR @ /pathblahblah/public_html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 1340) Could not get table class for class: MODX\Revolution\modAccess
[2022-06-29 10:54:53] (ERROR @ /pathblahblah/public_html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 1309) Could not get table name for class: MODX\Revolution\modAccess
[2022-06-29 10:54:53] (ERROR @ /pathblahblah/public_html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 227) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `modAccess` WHERE `modAccess`.`principal` = 14' at line 1
)
```

## Relevant context

The form submits successfully and the user email is sent, however, this email to the admin is not sent and generates an error. Using MODX 3

**Comment by Mark-H** [comment]
What's the server error? Check your server's PHP error log to find that.

**Comment by CamilleBeaute** [comment]
Hi Below is the server's PHP error:

```
Stack trace:
#0 /pathblahblah/public_html/core/components/login/processors/register.php(89): LoginRegisterProcessor->checkForRegisteredRedirect()
#1 /pathblahblah/public_html/core/components/login/model/login/logincontroller.class.php(213): LoginRegisterProcessor->process()
#2 /pathblahblah/public_html/core/components/login/controllers/web/Register.php(133): LoginController->runProcessor(Object(LoginRegisterProcessor))
#3 /pathblahblah/public_html/core/components/login/model/login/logincontroller.class.php(59): LoginRegisterController->process()
#4 /pathblahblah/public_html/core/cache/includes/elements/modx/revolution/modsnippet/20.include.cache.php(31): LoginController->run(Array)
#5/pathblahblah/public_html/core/src/Revolution/modScript.php(88): include('pathblahblah...')
#6 /pathblahblah/public_html/core/src/Revolution/modParser.php(505): MODX\Revolutio in /pathblahblah/public_html/core/components/login/processors/register.php on line 413
```

**Comment by Mark-H** [comment]
The error message is one line up from what you posted 😅

**Comment by CamilleBeaute** [comment]
Ahh sorry, I missed it when copying:

```[29-Jun-2022 10:55:43 America/Boise] PHP Fatal error:  Uncaught Error: Call to a member function get() on array in /pathblahblah/public_html/core/components/login/processors/register.php:413```

**Comment by Mark-H** [comment]
Doesn't look like a documentation issue. Please use the forum or post in the Login repository if you still haven't figured out the root cause.
